import argparse
import json
import sys
import time
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import yfinance as yf
from src.sp500_tickers import SP500_TICKERS
from src.notify import notify


WATCHLIST_PATH = Path("watchlist.txt")
DEFAULT_MIN_GAP_PCT = 3.0
DEFAULT_MIN_PRICE = 3.0
MAX_SURVIVORS = 20
ET = ZoneInfo("America/New_York")


def convert_to_yahoo_format(tickers):
    """Convert IBKR format to Yahoo format."""
    yahoo_tickers = []
    for ticker in tickers:
        if ticker.endswith(" B"):
            yahoo_tickers.append(ticker.replace(" B", "-B"))
        elif ticker.endswith(" A"):
            yahoo_tickers.append(ticker.replace(" A", "-A"))
        else:
            yahoo_tickers.append(ticker)
    return yahoo_tickers


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-gap", type=float, default=DEFAULT_MIN_GAP_PCT)
    parser.add_argument("--min-price", type=float, default=DEFAULT_MIN_PRICE)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    start_time = time.time()

    # Convert tickers to Yahoo format
    yahoo_tickers = convert_to_yahoo_format(SP500_TICKERS)

    # Download data
    try:
        data = yf.download(
            tickers=" ".join(yahoo_tickers),
            period="2d",
            interval="1d",
            group_by="ticker",
            threads=5,
            progress=False,
            auto_adjust=True,
        )
    except Exception as e:
        error_result = {
            "success": False,
            "total_screened": len(SP500_TICKERS),
            "survivors_count": 0,
            "below_gap": 0,
            "below_price": 0,
            "failed": len(SP500_TICKERS),
            "elapsed_seconds": time.time() - start_time,
            "top_20_survivors": [],
            "watchlist_path": str(WATCHLIST_PATH),
        }
        print(json.dumps(error_result))
        sys.exit(1)

    # Evaluate survivors
    survivors = []
    below_gap = 0
    below_price = 0
    failed = 0

    for i, ticker in enumerate(SP500_TICKERS):
        yahoo_ticker = yahoo_tickers[i]

        try:
            if yahoo_ticker not in data:
                failed += 1
                continue

            bars = data[yahoo_ticker]
            if len(bars) < 2:
                failed += 1
                continue

            yesterday_close = bars.iloc[-2]["Close"]
            today_open = bars.iloc[-1]["Open"]
            today_close = bars.iloc[-1]["Close"]
            today_high = bars.iloc[-1]["High"]
            today_low = bars.iloc[-1]["Low"]

            gap_pct = (today_close - yesterday_close) / yesterday_close * 100

            if today_close < args.min_price:
                below_price += 1
                continue

            if gap_pct < args.min_gap:
                below_gap += 1
                continue

            survivors.append(
                {
                    "ticker": ticker,
                    "gap_pct": float(gap_pct),
                    "open": float(today_open),
                    "close": float(today_close),
                    "high": float(today_high),
                    "low": float(today_low),
                    "prev_close": float(yesterday_close),
                }
            )

        except (KeyError, IndexError, ValueError):
            failed += 1
            continue

    # Sort by gap_pct descending and cap at MAX_SURVIVORS
    survivors.sort(key=lambda x: x["gap_pct"], reverse=True)
    survivors = survivors[:MAX_SURVIVORS]

    # Check degradation tripwires
    elapsed = time.time() - start_time
    degradation_alert = None
    if len(SP500_TICKERS) > 0:
        fail_ratio = failed / len(SP500_TICKERS)
        if fail_ratio >= 0.95:
            degradation_alert = "ALERT: Yahoo-wide failure suspected; check yfinance changelog"
            print(degradation_alert, file=sys.stderr)
        elif fail_ratio >= 0.30:
            degradation_alert = f"ALERT: yfinance degradation (failed {failed}/{len(SP500_TICKERS)})"
            print(degradation_alert, file=sys.stderr)

    # Write watchlist if not dry-run
    if not args.dry_run:
        now = datetime.now(ET)
        timestamp = now.strftime("%Y-%m-%d %H:%M %Z")

        with open(WATCHLIST_PATH, "w") as f:
            f.write(f"# Auto-generated by morning_prefilter.py at {timestamp}\n")
            f.write(f"# Filters: gap >= {args.min_gap}%, price >= ${args.min_price}\n")
            f.write("# Source: yfinance (screening only); IBKR handles execution\n")
            f.write(f"# Survivors: {len(survivors)} (capped at {MAX_SURVIVORS}) of {len(SP500_TICKERS)}\n")
            f.write("#\n")
            f.write("# ticker  # gap +X.XX%  open $X.XX  prev $X.XX\n")

            for s in survivors:
                gap_str = f"{s['gap_pct']:+.2f}"
                f.write(f"{s['ticker']}  # gap {gap_str}%  open ${s['open']:.2f}  prev ${s['prev_close']:.2f}\n")

    # Output JSON summary
    top_20_strings = [f"{s['ticker']} (+{s['gap_pct']:.2f}%)" for s in survivors]

    result = {
        "success": True,
        "total_screened": len(SP500_TICKERS),
        "survivors_count": len(survivors),
        "below_gap": below_gap,
        "below_price": below_price,
        "failed": failed,
        "elapsed_seconds": elapsed,
        "top_20_survivors": top_20_strings,
        "watchlist_path": str(WATCHLIST_PATH),
    }

    print(json.dumps(result))

    if not args.dry_run:
        now = datetime.now(ET)
        hhmm = now.strftime("%H:%M ET")
        if degradation_alert:
            notify(f"Prefilter DEGRADED {hhmm}", degradation_alert, "high")
        bullet_list = "\n".join(f"• {s}" for s in top_20_strings)
        notify(
            f"Prefilter {hhmm}",
            f"{len(survivors)}/{len(SP500_TICKERS)} survivors in {elapsed:.1f}s\n{bullet_list}",
            "default",
        )


if __name__ == "__main__":
    main()
