import argparse
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path
from statistics import mean
from zoneinfo import ZoneInfo

from ib_async import IB, Stock
from src.universe import get_combined_universe
from src.sp500_tickers import SP500_TICKERS
from src.notify import notify


WATCHLIST_PATH = Path("watchlist.txt")
DEFAULT_MIN_GAP_PCT = 3.0
DEFAULT_MIN_PRICE = 3.0
MAX_SURVIVORS = 40
ET = ZoneInfo("America/New_York")
MIN_AVG_DOLLAR_VOL = 10_000_000


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-gap", type=float, default=DEFAULT_MIN_GAP_PCT)
    parser.add_argument("--min-price", type=float, default=DEFAULT_MIN_PRICE)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    start_time = time.time()

    # Connect to IBKR
    ib = IB()
    client_id = int(os.getenv("IBKR_CLIENT_ID_PREFILTER", "3"))
    try:
        ib.connect(
            os.getenv("IBKR_HOST", "127.0.0.1"),
            int(os.getenv("IBKR_PORT", "7497")),
            clientId=client_id,
        )
    except Exception as e:
        print(f"ERROR: Could not connect to IBKR: {e}", file=sys.stderr)
        sys.exit(1)

    universe = get_combined_universe()
    sp500_set = set(SP500_TICKERS)

    survivors = []
    below_gap = 0
    below_price = 0
    below_dollar_vol = 0
    failed = 0

    for ticker in universe:
        contract = Stock(ticker, "SMART", "USD")
        try:
            ib.qualifyContracts(contract)
        except Exception:
            failed += 1
            continue

        try:
            bars = ib.reqHistoricalData(
                contract,
                endDateTime="",
                durationStr="3 D",
                barSizeSetting="1 day",
                whatToShow="TRADES",
                useRTH=True,
                keepUpToDate=False,
            )
            time.sleep(0.05)
        except Exception:
            failed += 1
            continue

        if not bars or len(bars) < 2:
            failed += 1
            continue

        try:
            yesterday_close = bars[-2].close
            today_open = bars[-1].open
            today_close = bars[-1].close
            today_high = bars[-1].high
            today_low = bars[-1].low

            gap_pct = (today_close - yesterday_close) / yesterday_close * 100

            if today_close < args.min_price:
                below_price += 1
                continue

            if gap_pct < args.min_gap:
                below_gap += 1
                continue

            # Liquidity filter: skip for S&P 500 names (already liquid)
            if ticker not in sp500_set:
                recent_bars = bars[-20:] if len(bars) >= 20 else bars
                dollar_vols = [b.close * b.volume for b in recent_bars if b.volume > 0]
                if dollar_vols:
                    avg_dollar_vol = mean(dollar_vols)
                    if avg_dollar_vol < MIN_AVG_DOLLAR_VOL:
                        below_dollar_vol += 1
                        continue

            survivors.append(
                {
                    "ticker": ticker,
                    "gap_pct": float(gap_pct),
                    "open": float(today_open),
                    "close": float(today_close),
                    "high": float(today_high),
                    "low": float(today_low),
                    "prev_close": float(yesterday_close),
                }
            )

        except (AttributeError, IndexError, ValueError, ZeroDivisionError):
            failed += 1
            continue

    # Disconnect IBKR before writing watchlist
    try:
        ib.disconnect()
    except Exception:
        pass

    # Sort by gap_pct descending and cap at MAX_SURVIVORS
    survivors.sort(key=lambda x: x["gap_pct"], reverse=True)
    survivors = survivors[:MAX_SURVIVORS]

    elapsed = time.time() - start_time

    # Write watchlist if not dry-run
    if not args.dry_run:
        now = datetime.now(ET)
        timestamp = now.strftime("%Y-%m-%d %H:%M %Z")

        with open(WATCHLIST_PATH, "w") as f:
            f.write(f"# Auto-generated by morning_prefilter.py at {timestamp}\n")
            f.write(f"# Filters: gap >= {args.min_gap}%, price >= ${args.min_price}\n")
            f.write("# Source: IBKR (prefilter); earnings check not implemented\n")
            f.write(f"# Survivors: {len(survivors)} (capped at {MAX_SURVIVORS}) of {len(universe)}\n")
            f.write("#\n")
            f.write("# ticker  # gap +X.XX%  open $X.XX  prev $X.XX\n")

            for s in survivors:
                gap_str = f"{s['gap_pct']:+.2f}"
                f.write(f"{s['ticker']}  # gap {gap_str}%  open ${s['open']:.2f}  prev ${s['prev_close']:.2f}\n")

    # Output JSON summary
    top_survivors_strings = [f"{s['ticker']} (+{s['gap_pct']:.2f}%)" for s in survivors]

    result = {
        "success": True,
        "total_screened": len(universe),
        "survivors_count": len(survivors),
        "below_gap": below_gap,
        "below_price": below_price,
        "below_dollar_vol": below_dollar_vol,
        "failed": failed,
        "elapsed_seconds": elapsed,
        "top_20_survivors": top_survivors_strings,
        "watchlist_path": str(WATCHLIST_PATH),
    }

    print(json.dumps(result))

    if not args.dry_run:
        now = datetime.now(ET)
        hhmm = now.strftime("%H:%M ET")
        bullet_list = "\n".join(f"• {s}" for s in top_survivors_strings)
        notify(
            f"Prefilter {hhmm}",
            f"{len(survivors)}/{len(universe)} survivors in {elapsed:.1f}s\n{bullet_list}",
            "default",
        )


if __name__ == "__main__":
    main()
